require('dotenv').config()
const exp=require('express')
const cors=require('cors')
const { connectDB } = require('./config/db')
const { notFound, errorHandler } = require('./middleware/errorHandler')

const emailApp=require('./Apis/emailApi')
const farmerApp=require('./Apis/farmerApi')
const contactApp=require('./Apis/ContactApi')
const authApp=require('./Apis/authApi')
const labourApp=require('./Apis/labourApi')
const jobApp=require('./Apis/jobApi')
const adminApp=require('./Apis/adminApi')
const messageApp=require('./Apis/messageApi')
const reviewApp=require('./Apis/reviewApi')
const notifApp=require('./Apis/notificationApi')
const paymentApp=require('./Apis/paymentApi')

const app=exp()
app.use(cors())
app.use(exp.json())

app.use('/auth',authApp)
app.use('/farmer-api',farmerApp)
app.use('/labour-api',labourApp)
app.use('/',jobApp)
app.use('/email-api',emailApp)
app.use('/contact-api',contactApp)
app.use('/admin',adminApp)
app.use('/',messageApp)
app.use('/',reviewApp)
app.use('/',notifApp)
app.use('/',paymentApp)

app.use(notFound)
app.use(errorHandler)

const port=process.env.PORT || 4000
connectDB(process.env.DBURL)
  .then(()=>{
      app.listen(port,()=>console.log(`connection on ${port}`))
      console.log("Database Connected Successfully")
  })
  .catch((err)=>{
      console.log(err)
      process.exit(1)
  })
