const mongoose = require("mongoose");

const farmerLabourSchema=new mongoose.Schema({
  role:{
    type:String,
    required:true,
    enum:['farmer','labour','admin']
  },
  email:{
    type:String,
    required:true,
    unique:true
  },
  password:{
    type:String,
    required:true,
    minlength:6
  },
  firstName:{
    type:String,
    required:true
  },
  lastName:{
    type:String,
    default:''
  },
  phoneNo:{
    type:String,
    default:''
  },
  location:{
    type:String,
    default:''
  },
  skills:{
    type:[String],
    default:[]
  },
  tools:{
    type:[String],
    default:[]
  },
  experienceYears:{
    type:Number,
    default:0
  },
  preferredWage:{
    type:Number
  },
  availability:{
    type:String,
    default:''
  },
  languages:{
    type:[String],
    default:[]
  },
  profileImageUrl:{
    type:String,
    default:''
  },
  isActive:{
    default:true,
    type:Boolean
  }

},{'strict':'throw'})
const farmerLabourModel=mongoose.model('farmerlabour',farmerLabourSchema)
module.exports=farmerLabourModel; 
